### ISSUE TITLE
redis配置的问题

### ISSUE THREAD

**Issue by wang2650** [geffzhang/NanoFabric#4]
你的实例项目SampleService.IdentityServer  默认不会从配置文件里取redis配置

**Comment by wang2650** [comment]
就是不会从appsettings里读取。所以如果直接运行这个实例的话，redis链接会报错

**Comment by geffzhang** [comment]
是，功能还没加上

**Comment by rocketRobin** [comment]
可以，关注了

**Comment by rocketRobin** [comment]
原来是张善友老师！

**Comment by coolincy** [comment]
代码里redis的配置跑到logging里，不会生效，需要移出来，如下所示
{
    "Logging": {
        "IncludeScopes": false,
        "LogLevel": {
            "Default": "Debug",
            "System": "Information",
            "Microsoft": "Information"
        }
    },
    "IdentityOptions": {
        "Redis": "192.168.1.10:6379,password=xxxxx",
        "DbNum": 2
    }
}
